### ISSUE TITLE
关于SideBarFolders插件不可用的问题

### ISSUE THREAD

**Issue by qiqihaobenben** [nicejade/sublime_packages#1]
把你这个插件包加到本地去，每次打开ST都会提示这个插件不可用，加入到ignored_packages列表中，有意思的是打开编辑器，会在ignored_packages中先把这个插件移出去，提示不可用后，再加进来。希望看到后帮助解决一下。

**Comment by nicejade** [comment]
抱歉，才关注到这里；对于这个问题，也是很疑惑。已经 remove 了该插件，并在 ignored_packages  予以忽视，却总还是提示；并且去掉 ignored_packages 中的忽视，也总会被自动注入进去，实在令人不解。目前来看，最佳的处理办法是重新安装一套，然后备份。

**Comment by qiqihaobenben** [comment]
是的，第二次就轻车熟路的装了。谢谢回复。

在 2017-05-05 17:18:45，"JadeYang(杨琼璞)" <notifications@github.com> 写道：


抱歉，才关注到这里；对于这个问题，也是很疑惑。已经 remove 了该插件，并在 ignored_packages 予以忽视，却总还是提示；并且去掉 ignored_packages 中的忽视，也总会被自动注入进去，实在令人不解。目前来看，最佳的处理办法是重新安装一套，然后备份。

**Comment by nicejade** [comment]
最新更新的备份中，已经去掉了这个插件（SideBarFolders）。
